[project]
name = "hotel-cancellation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3<1.43",
    "fastapi>=0.136.3",
    "great-expectations>=1.17.2",
    "mlflow>=1.27.0",
    "pandas>=3.0.3",
    "polars>=1.41.2",
    "pyarrow>=24.0.0",
    "pydantic-settings>=2.14.1",
    "s3fs>=2024.0",
    "scikit-learn>=1.8.0",
    "uvicorn[standard]>=0.48.0",
    "xgboost>=3.2.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.15",
]
